// app/src/app/components/Home.tsx
import React, { useState, useEffect } from 'react';
import { Link } from 'react-router-dom';
import generateId from '../conferenceRoom/idGenerator';

const Home: React.FC = () => {
  const [username, setUsername] = useState('');
  const [roomId, setRoomId] = useState('')

  useEffect(() => {
    const newRoomId = generateId();
    setRoomId(newRoomId.getValue());
  }, [username]);

  return (
    <div className="mt-12 mb-12 flex flex-col items-center">
      <div>
        Welcome to UVID
    </div>
      <div>
        <input
          className="text-black text-center"
          type="text"
          placeholder="Please enter your name"
          onChange={(e) => setUsername(e.target.value)} />
      </div>
      <div>
        <Link to={`/conferenceRoom/${username}/${roomId}`}>
          <button>
            Create a room
          </button>
        </Link>
      </div>
    </div>
  )
};

export default Home;

// app/src/components/Home.vue
<template>
  <div id="signin-form">
    <div>
        <input type="text" v-model="username" placeholder="Enter your username">
    </div>
    <div>
        <button v-on:click="createNewRoom">
          Create room
        </button>
    </div>
  </div>
</template>

<script>
import generateId from '../roomIdGenerator/idGenerator';

export default {
  name: 'Home',
  data: () => ({
      username: '',

  }),
  methods: {
    createNewRoom() {
      if (this.username) {
        const roomId = generateId();
        this.$router.push({ name: 'Room', params: { roomId } });
      }
    }
  },
}
</script>

<style scoped>
#signin-form {
  display: flex;
  flex-direction: column;
}
</style>
